CREATE TABLE channel_asset (
  id BINARY(16) NOT NULL,
  channel_key VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  scope VARCHAR(16) NOT NULL DEFAULT 'PERSONAL',
  type VARCHAR(32) NOT NULL,
  bound_agent_id BINARY(16) NULL,
  owner_user_id VARCHAR(128) NOT NULL DEFAULT '',
  dm_scope VARCHAR(32) NOT NULL DEFAULT 'PER_PEER',
  config_json TEXT NOT NULL,
  secrets_ciphertext TEXT NULL,
  secrets_configured_json TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  runtime_status VARCHAR(16) NOT NULL DEFAULT 'STOPPED',
  last_error TEXT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system',
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_key (channel_key),
  KEY idx_channel_bound_agent (bound_agent_id),
  CONSTRAINT fk_channel_agent FOREIGN KEY (bound_agent_id) REFERENCES agent_asset(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
