CREATE TABLE product (
  id BINARY(16) NOT NULL,
  product_key VARCHAR(128) NOT NULL,
  source_id BINARY(16) NULL,
  external_id VARCHAR(255) NULL,
  name VARCHAR(255) NOT NULL,
  brand VARCHAR(128) NOT NULL DEFAULT '',
  category VARCHAR(128) NOT NULL DEFAULT '',
  price_min DECIMAL(14,2) NULL,
  price_max DECIMAL(14,2) NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
  spec_json TEXT NOT NULL,
  selling_points MEDIUMTEXT NULL,
  scenario_tags_json TEXT NOT NULL,
  images_json TEXT NOT NULL,
  description MEDIUMTEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  weight INT NOT NULL DEFAULT 100,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  updated_by VARCHAR(64) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_key (product_key),
  UNIQUE KEY uk_product_source_external (source_id, external_id),
  KEY idx_product_category (category),
  KEY idx_product_status (status),
  KEY idx_product_source (source_id),
  CONSTRAINT fk_product_source FOREIGN KEY (source_id) REFERENCES product_source(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
