import { useState, type ReactNode } from 'react'

type Page = 'agents' | 'models' | 'skills' | 'mcp' | 'memory' | 'workspace' | 'teams' | 'release' | 'observe'

const modules: { id: Page; icon: string; name: string; kicker: string }[] = [
  { id: 'agents', icon: '◈', name: '智能体', kicker: 'HARNESS AGENT' },
  { id: 'models', icon: '◌', name: '模型策略', kicker: 'MODEL POLICY' },
  { id: 'skills', icon: '✦', name: '技能仓库', kicker: 'SKILL MARKET' },
  { id: 'mcp', icon: '⌘', name: 'MCP 与工具', kicker: 'TOOLS CONFIG' },
  { id: 'memory', icon: '◫', name: '记忆与上下文', kicker: 'MEMORY + CONTEXT' },
  { id: 'workspace', icon: '▤', name: '工作空间', kicker: 'WORKSPACE' },
  { id: 'teams', icon: '⊹', name: '子 Agent 与协作', kicker: 'COLLABORATION' },
  { id: 'release', icon: '↗', name: '发布与环境', kicker: 'RELEASE SNAPSHOT' },
  { id: 'observe', icon: '◌', name: '运行观测', kicker: 'RUNTIME OBSERVE' },
]

function Button({ children, quiet = false, onClick }: { children: ReactNode; quiet?: boolean; onClick?: () => void }) {
  return <button onClick={onClick} className={quiet ? 'ui-button quiet' : 'ui-button'}>{children}</button>
}

function Toggle({ on, setOn, label }: { on: boolean; setOn: (next: boolean) => void; label?: string }) {
  return <button aria-label={label} onClick={() => setOn(!on)} className={`toggle ${on ? 'on' : ''}`}><i /></button>
}

function Field({ label, value, hint, wide = false }: { label: string; value: string; hint?: string; wide?: boolean }) {
  return <label className={`field ${wide ? 'wide' : ''}`}><span>{label}</span><input defaultValue={value} />{hint && <small>{hint}</small>}</label>
}

function PageHeader({ kicker, title, description, action }: { kicker: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="page-header"><div><p className="kicker">{kicker}</p><h1>{title}</h1><p className="page-description">{description}</p></div>{action}</header>
}

function AgentPage({ go }: { go: (page: Page) => void }) {
  const [selected, setSelected] = useState('customer-service')
  const agents = [['customer-service', '客户服务中枢', 'PROD', '24'], ['knowledge-router', '知识路由器', 'CANARY', '8'], ['finance-analyst', '财务分析师', 'DRAFT', '—']]
  return <><PageHeader kicker="HARNESS AGENT / REGISTRY" title="智能体编排台" description="围绕 HarnessAgent 定义可发布的运行规格，并将配置固定为不可变快照。" action={<Button>＋ 创建智能体</Button>} />
    <div className="agent-workbench"><aside className="sub-rail"><div className="search-mini">⌕ 搜索智能体</div><p>AGENT REGISTRY <b>03</b></p>{agents.map(([id, name, state, runs]) => <button key={id} onClick={() => setSelected(id)} className={selected === id ? 'agent-select selected' : 'agent-select'}><span className="agent-icon">◈</span><span><b>{name}</b><small>{id}</small></span><em className={state.toLowerCase()}>{state}</em></button>)}<button className="add-list">＋ 新建 Draft</button></aside>
      <section className="agent-detail"><div className="detail-title"><div className="large-agent-icon">◈</div><div><p className="kicker">AGENT / {selected.toUpperCase()}</p><h2>客户服务中枢 <span className="tag blue">PROD</span></h2><small>customer-service · revision 18 · snapshot 8f1a09c</small></div><div className="detail-actions"><Button quiet>◷ 历史版本</Button><Button>发布变更 →</Button></div></div>
        <div className="agent-tabs"><button className="tab active">概览</button><button className="tab" onClick={() => go('workspace')}>工作空间</button><button className="tab" onClick={() => go('mcp')}>工具</button><button className="tab" onClick={() => go('memory')}>记忆</button><button className="tab" onClick={() => go('observe')}>运行记录</button></div>
        <div className="agent-overview"><article className="harness-card blueprint"><p className="kicker">HARNESS SPEC</p><div className="spec-flow"><span>Prompt</span><i>→</i><span>Model</span><i>→</i><span>Tools</span><i>→</i><span>Memory</span></div><div className="spec-lines"><p><b>modelPolicy</b> <code>qwen-production@v3</code></p><p><b>toolPolicy</b> <code>safe-crm@v2</code></p><p><b>memoryPolicy</b> <code>user-profile@v4</code></p><p><b>environment</b> <code>prod-cn-sh@v2</code></p></div><button onClick={() => go('release')} className="link-button">查看 ReleaseSnapshot →</button></article>
          <article className="harness-card"><p className="kicker">RUNTIME HEALTH</p><div className="health-score">99.98<small>%</small></div><div className="health-bars"><span><i style={{ width: '96%' }} />模型</span><span><i style={{ width: '100%' }} />工具</span><span><i style={{ width: '83%' }} />上下文</span></div><small>当前 24 个活跃会话 · P95 1.84s</small></article>
          <article className="harness-card activity"><p className="kicker">LATEST CHANGE</p><b>memory-policy@v4</b><p>更新每日记忆整合频率，从 30 分钟调整为 2 小时。</p><small>由 NEASON · 14:32:06</small><button className="link-button">查看差异 →</button></article></div>
      </section></div></>
}

function ModelsPage() { const [provider, setProvider] = useState('Qwen'); return <><PageHeader kicker="MODEL POLICY / ROUTING" title="模型策略" description="配置 HarnessAgent 的主模型、生成参数、故障降级和执行预算。" action={<Button>＋ 新建策略</Button>} /><div className="config-layout"><aside className="sub-rail provider-list"><p>MODEL POLICY <b>04</b></p>{['qwen-production@v3', 'openai-reasoning@v2', 'deepseek-cost@v1', 'local-ollama@v1'].map((x, i) => <button className={i === 0 ? 'agent-select selected' : 'agent-select'} key={x}><span className="agent-icon">{['Q', 'O', 'D', 'L'][i]}</span><span><b>{x}</b><small>{i === 0 ? 'default / prod' : 'available'}</small></span></button>)}</aside><section className="form-surface"><div className="form-title"><div><p className="kicker">POLICY / QWEN-PRODUCTION@V3</p><h2>生产模型路由</h2></div><span className="tag blue">DEFAULT</span></div><div className="provider-pills">{['Qwen', 'OpenAI', 'DeepSeek', 'Anthropic', 'Ollama'].map(x => <button onClick={() => setProvider(x)} className={provider === x ? 'provider active' : 'provider'} key={x}>{x}</button>)}</div><div className="field-grid"><Field label="主模型" value={provider === 'Qwen' ? 'qwen-plus' : `${provider.toLowerCase()}-model`} /><Field label="降级模型" value="qwen-turbo" /><Field label="最大迭代次数" value="12" hint="HarnessAgent.maxIters" /><Field label="模型重试次数" value="2" hint="ModelConfig.maxRetries" /></div><section className="section-block"><div className="section-label"><b>生成参数</b><small>GenerateOptions</small></div><div className="range-row"><span>Temperature <b>0.20</b></span><input type="range" min="0" max="1" step=".05" defaultValue=".2" /><span>Top P <b>0.85</b></span><input type="range" min="0" max="1" step=".05" defaultValue=".85" /></div></section><section className="section-block switch-line"><div><b>结构化输出</b><small>为指定 Run 启用 JSON Schema 响应校验</small></div><Toggle on={true} setOn={() => {}} /></section><div className="sticky-actions"><Button quiet>放弃更改</Button><Button>保存模型策略</Button></div></section></div></> }

function SkillsPage() { const [enabled, setEnabled] = useState([true, true, false]); const skills = [['product-faq', '产品知识问答', 'v11 · 12 references'], ['ticket-writing', '工单编写规范', 'v3 · 2 scripts'], ['self-reflection', '自我复盘草稿', 'v1-draft · review required']]; return <><PageHeader kicker="SKILL MARKET / BINDING" title="技能仓库" description="按优先级绑定 AgentSkillRepository；发布时锁定 Skill 的内容 hash 与版本。" action={<Button>＋ 导入 Skill</Button>} /><div className="content-split"><section className="catalog-panel"><div className="catalog-header"><div className="search-mini">⌕ 搜索技能资产</div><button className="filter-chip">全部来源⌄</button></div>{skills.map(([id, name, meta], i) => <article className="skill-row" key={id}><div className="skill-glyph">✦</div><div><b>{name}</b><code>{id}</code><small>{meta}</small></div><Toggle on={enabled[i]} setOn={(next) => setEnabled(current => current.map((v, index) => index === i ? next : v))} label={`toggle ${name}`} /></article>)}</section><aside className="binding-panel"><p className="kicker">RESOLUTION ORDER</p><h2>加载优先级</h2><div className="priority-list"><div><b>01</b><span>平台基础库<small>project-global</small></span></div><div><b>02</b><span>已绑定市场<small>marketplace repository</small></span></div><div className="highlight"><b>03</b><span>当前工作空间<small>workspace/skills</small></span></div><div><b>04</b><span>用户覆盖层<small>&lt;userId&gt;/skills</small></span></div></div><section className="policy-note"><b>生产保护</b><p>草稿 Skill 必须经 Promotion Gate 审核后才可在 prod 可见。</p></section><Button>保存绑定</Button></aside></div></> }

function McpPage() { const [server, setServer] = useState('crm'); return <><PageHeader kicker="TOOLS CONFIG / MCP" title="MCP 与工具策略" description="受管 MCP 以 SecretRef 连接，并使用 allow/deny 对可执行工具面进行最小化控制。" action={<Button>＋ 注册 MCP</Button>} /><div className="config-layout"><aside className="sub-rail"><p>MCP SERVERS <b>03</b></p>{[['crm', 'CRM 服务', 'HTTP'], ['knowledge', '知识检索', 'SSE'], ['internal-db', '内网数据工具', 'STDIO']].map(([id, name, type]) => <button onClick={() => setServer(id)} className={server === id ? 'agent-select selected' : 'agent-select'} key={id}><span className="agent-icon">⌘</span><span><b>{name}</b><small>{type} · healthy</small></span><i className="ok-dot" /></button>)}</aside><section className="form-surface"><div className="form-title"><div><p className="kicker">MCP BINDING / {server.toUpperCase()}</p><h2>{server === 'crm' ? 'CRM 服务' : '知识检索服务'}</h2></div><span className="tag green">HEALTHY</span></div><div className="field-grid"><Field label="传输协议" value={server === 'crm' ? 'streamable-http' : 'sse'} /><Field label="SecretRef" value="secrets/prod/crm-api" /><Field label="服务地址" value={server === 'crm' ? 'https://mcp.ok-agent.internal/crm' : 'https://mcp.ok-agent.internal/search'} wide /><Field label="调用超时" value="PT15S" /><Field label="初始化超时" value="PT8S" /></div><section className="tool-policy"><div className="section-label"><b>允许的工具</b><small>enableTools · 未列出的 server tools 不会注册</small></div>{['search_customer', 'get_ticket', 'create_ticket', 'update_ticket'].map((tool, index) => <label key={tool} className="tool-check"><input defaultChecked={index < 3} type="checkbox" /><span>{tool}</span><small>{index === 2 ? 'ask · requires HITL' : 'allow'}</small></label>)}</section><div className="sticky-actions"><Button quiet>测试连接</Button><Button>保存 MCP 绑定</Button></div></section></div></> }

function MemoryPage() { const [tab, setTab] = useState<'memory' | 'context'>('memory'); return <><PageHeader kicker="MEMORY + CONTEXT POLICY" title="记忆与上下文" description="区分跨会话长期记忆和会话内上下文压缩，分别控制成本、保留与可恢复性。" /><div className="tab-switch"><button onClick={() => setTab('memory')} className={tab === 'memory' ? 'active' : ''}>长期记忆 / MemoryConfig</button><button onClick={() => setTab('context')} className={tab === 'context' ? 'active' : ''}>上下文压缩 / CompactionConfig</button></div>{tab === 'memory' ? <section className="policy-canvas"><article className="pipeline-card"><p className="kicker">LONG-TERM MEMORY PIPELINE</p><div className="memory-flow"><span>对话结束</span><i>→</i><span>Flush</span><i>→</i><span>Daily Ledger</span><i>→</i><span>Consolidation</span><i>→</i><span>MEMORY.md</span></div><small>MEMORY.md 会在每个 reasoning step 注入系统提示词；每日日志仅作为可审计原始事实。</small></article><div className="form-columns"><section className="form-surface compact"><div className="section-label"><b>记忆抽取</b><small>MemoryFlushMiddleware</small></div><Field label="辅助模型" value="qwen-turbo" /><Field label="Flush Trigger" value="THROTTLED / PT10M" /><Field label="抽取提示词" value="提取长期有效的用户偏好、任务事实和明确决策。" wide /><div className="switch-line"><div><b>每次调用后抽取</b><small>关闭后仍会在压缩前和溢出恢复时执行</small></div><Toggle on={false} setOn={() => {}} /></div></section><section className="form-surface compact"><div className="section-label"><b>整合与保留</b><small>MemoryMaintenanceMiddleware</small></div><Field label="MEMORY.md token 上限" value="4000" /><Field label="最小整合间隔" value="PT2H" /><Field label="每日账本保留" value="90 days" /><Field label="会话日志保留" value="180 days" /></section></div></section> : <section className="policy-canvas"><article className="pipeline-card blue-tone"><p className="kicker">CONVERSATION COMPACTION</p><div className="memory-flow"><span>Context Window</span><i>→</i><span>Flush</span><i>→</i><span>Offload</span><i>→</i><span>Summary</span><i>→</i><span>Recent Tail</span></div><small>默认动态依据模型 context window 触发，并保留按 token 计算的最近消息尾部。</small></article><div className="form-columns"><section className="form-surface compact"><Field label="压缩触发 token" value="dynamic (window - 20k)" /><Field label="最近上下文保留" value="dynamic / 25% usable" /><Field label="摘要模型" value="qwen-turbo" /></section><section className="form-surface compact"><Field label="工具结果卸载阈值" value="80,000 chars" /><Field label="参数截断" value="2,000 chars" /><div className="switch-line"><div><b>压缩前写入原始消息</b><small>保留 JSONL 用于运行审计与 session_search</small></div><Toggle on={true} setOn={() => {}} /></div></section></div></section>}</> }

function WorkspacePage() { return <><PageHeader kicker="WORKSPACE / FILESYSTEM" title="工作空间与执行环境" description="将 Workspace Context、文件系统隔离和 Sandbox 能力绑定到部署环境，而非暴露给普通编辑者。" action={<Button>编辑环境模板</Button>} /><div className="workspace-grid"><section className="file-tree panel-lite"><div className="tree-title"><b>workspace / customer-service</b><span className="tag blue">REMOTE FS</span></div>{['AGENTS.md', 'MEMORY.md', 'tools.json', 'knowledge/', 'skills/', 'subagents/', 'plans/', 'agents/customer-service/sessions/'].map((x, index) => <p key={x} className={index < 3 ? 'file' : 'folder'}><span>{index < 3 ? '□' : '⌁'}</span>{x}{index === 1 && <em>injected</em>}</p>)}</section><section className="workspace-config"><article className="form-surface"><div className="section-label"><b>运行时投影</b><small>WorkspaceContextMiddleware</small></div><Field label="Workspace Template" value="workspace-template/customer-service@v5" wide /><Field label="额外上下文文件" value="knowledge/product.md, knowledge/ticket-rules.md" wide /><Field label="最大上下文预算" value="8,000 tokens" /><div className="switch-line"><div><b>@ 路径展开</b><small>将 @file 指向的 workspace 内容安全地载入上下文</small></div><Toggle on={true} setOn={() => {}} /></div></article><article className="form-surface"><div className="section-label"><b>隔离与 Sandbox</b><small>SandboxFilesystemSpec</small></div><div className="environment-card"><span>ISOLATION SCOPE</span><b>USER</b><small>同一用户跨 Session 共享受控文件视图；生产环境禁止 LocalFilesystemSpec。</small></div><div className="switch-line"><div><b>工作空间投影</b><small>启动 sandbox 时投影 AGENTS.md、skills、knowledge 等根目录</small></div><Toggle on={true} setOn={() => {}} /></div></article></section></div></> }

function TeamsPage() { const [plan, setPlan] = useState(false); return <><PageHeader kicker="COLLABORATION / PLAN MODE" title="子 Agent 与协作" description="声明受限角色、后台任务和计划模式；复杂协作在发布前完成权限与最大深度校验。" action={<Button>＋ 添加子 Agent</Button>} /><div className="team-canvas"><section className="team-map"><div className="parent-node"><i>◈</i><b>客户服务中枢</b><small>lead / qwen-plus</small></div><div className="branch one" /><div className="branch two" /><div className="child-node node-one"><i>◫</i><b>知识检索</b><small>sync · read-only tools</small></div><div className="child-node node-two"><i>⌘</i><b>工单执行</b><small>background · HITL</small></div><p className="kicker map-label">SUBAGENT DECLARATIONS</p></section><section className="form-surface"><div className="section-label"><b>协作运行策略</b><small>SubagentsMiddleware / MessageBus</small></div><Field label="最大委派深度" value="2" /><Field label="后台任务超时" value="PT5M" /><Field label="Task Repository" value="distributed/task-store@v1" wide /><div className="switch-line"><div><b>动态子 Agent</b><small>读取 workspace/subagents 下的声明，并在每个 call 前重载</small></div><Toggle on={true} setOn={() => {}} /></div><div className="switch-line"><div><b>Plan Mode</b><small>为会话注册 plan_enter / plan_write / plan_exit；默认严格只读</small></div><Toggle on={plan} setOn={setPlan} /></div>{plan && <div className="warning-note">Plan Mode 当前启用。Shell 仍保持拒绝；退出计划模式后才允许修改或执行敏感工具。</div>}</section></div></> }

function ReleasePage() { const [step, setStep] = useState(2); return <><PageHeader kicker="RELEASE SNAPSHOT / DEPLOYMENT" title="发布与环境" description="将所有资产引用解析、冻结并签名为 ReleaseSnapshot；运行态只读取快照而不读取 Draft。" action={<Button>创建发布</Button>} /><div className="release-workspace"><section className="release-timeline">{[['01', 'Draft revision', '18'], ['02', 'Validation', 'passed'], ['03', 'Release snapshot', '8f1a09c'], ['04', 'Deployment', 'prod-cn-sh']].map((x, index) => <button onClick={() => setStep(index)} className={index <= step ? 'release-step done' : 'release-step'} key={x[0]}><b>{x[0]}</b><span>{x[1]}<small>{x[2]}</small></span>{index === step && <i>●</i>}</button>)}</section><section className="snapshot-panel"><div className="form-title"><div><p className="kicker">SNAPSHOT / 8F1A09C</p><h2>生产发布包</h2></div><span className="tag green">READY</span></div><div className="manifest-list">{[['agentRevision', 'customer-service@18'], ['modelPolicy', 'qwen-production@3'], ['skillBindings', 'product-faq@11, ticket-writing@3'], ['mcpBindings', 'crm@7'], ['memoryPolicy', 'user-profile@4'], ['environment', 'prod-cn-sh@2']].map(([key, value]) => <p key={key}><b>{key}</b><code>{value}</code><span>✓ locked</span></p>)}</div><div className="deploy-bar"><p><span>DEPLOYMENT TRAFFIC</span><b>100% / prod</b></p><div><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="sticky-actions"><Button quiet>查看差异</Button><Button>部署到生产 →</Button></div></section></div></> }

function ObservePage() { const [query, setQuery] = useState(''); const runs = [['run_839f', 'customer-service', 'completed', '1.42s', '3,821'], ['run_827a', 'customer-service', 'waiting_hitl', '—', '1,224'], ['run_812d', 'knowledge-router', 'completed', '0.89s', '1,096'], ['run_7fe1', 'finance-analyst', 'failed', '4.33s', '6,421']]; return <><PageHeader kicker="RUNTIME OBSERVE / TRACE" title="运行观测" description="以 tenant、snapshot、session、run 和 trace 为关联键，回放完整的模型、工具与权限决策链路。" action={<Button>导出 Trace</Button>} /><div className="observe-summary"><article><span>24</span><small>ACTIVE RUNS</small></article><article><span>99.2%</span><small>TOOL SUCCESS</small></article><article><span>1.84s</span><small>P95 LATENCY</small></article><article><span>¥18.67</span><small>TODAY COST</small></article></div><section className="run-table"><div className="table-tools"><div className="search-mini">⌕ <input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索 Run ID、Session 或 Agent" /></div><button className="filter-chip">近 24 小时⌄</button><button className="filter-chip">全部状态⌄</button></div><div className="table-head"><span>RUN</span><span>AGENT / SNAPSHOT</span><span>STATUS</span><span>LATENCY</span><span>TOKENS</span><span /></div>{runs.filter(x => x.join(' ').includes(query)).map(row => <button className="table-row" key={row[0]}><code>{row[0]}</code><span><b>{row[1]}</b><small>snapshot 8f1a09c</small></span><em className={row[2]}>{row[2]}</em><span>{row[3]}</span><span>{row[4]}</span><i>→</i></button>)}</section></> }

export default function App() {
  const [page, setPage] = useState<Page>('agents')
  const [notice, setNotice] = useState('')
  const selected = modules.find(x => x.id === page)!
  const navigate = (next: Page) => { setPage(next); setNotice(`${modules.find(x => x.id === next)?.name} 已切换`) }
  const content = { agents: <AgentPage go={navigate} />, models: <ModelsPage />, skills: <SkillsPage />, mcp: <McpPage />, memory: <MemoryPage />, workspace: <WorkspacePage />, teams: <TeamsPage />, release: <ReleasePage />, observe: <ObservePage /> }[page]
  return <main className="console-shell"><aside className="main-nav"><div className="brand"><span className="brand-mark">ok</span><span>AGENT</span></div><p className="nav-caption">HARNESS CONTROL PLANE</p><nav>{modules.map((module, index) => <button key={module.id} onClick={() => navigate(module.id)} className={page === module.id ? 'module-link active' : 'module-link'}><i>{module.icon}</i><span>{module.name}</span><small>0{index + 1}</small></button>)}</nav><div className="nav-footer"><i className="ok-dot" /> CN-SH-01 / HEALTHY<br/><small>AGENTSCOPE JAVA 2.0</small></div></aside><section className="app-content"><header className="app-topbar"><div><span className="crumb">控制面</span><i>/</i><b>{selected.name}</b></div><div><button className="top-search">⌕ 搜索 <kbd>⌘ K</kbd></button><button className="icon-button">◌</button><button className="icon-button">◐</button><span className="avatar">N</span></div></header>{notice && <button className="toast" onClick={() => setNotice('')}>✓ {notice}</button>}<section className="page-content" key={page}>{content}</section></section></main>
}
